# Generated by Django 3.2.13 on 2022-06-22 03:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_alter_uploadedimage_user'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='presets',
            field=models.ManyToManyField(related_name='plans', to='images.ImagePreset'),
        ),
        migrations.AlterField(
            model_name='user',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscribed_users', to='accounts.plan'),
        ),
    ]
