version: "3.9"
services:
  cache:
    image: redis:alpine
    ports:
      - "${REDIS_PORT:-6379}:${REDIS_PORT:-6379}"
    volumes:
      - ./redis_data:/data

  db:
    image: postgres:alpine
    ports:
      - "${POSTGRES_PORT:-5432}:${POSTGRES_PORT:-5432}"
    volumes:
      - ./db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-image_api_user}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-image_api_password}
      - POSTGRES_DB=${POSTGRES_DB:-image_api_db}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    image: disco_image_api:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${APP_PORT:-8000}:${APP_PORT:-8000}"
    volumes:
      - ./image_api:/app
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-image_api_user}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-image_api_password}
      - POSTGRES_DB=${POSTGRES_DB:-image_api_db}
      - POSTGRES_HOST=${POSTGRES_HOST:-db}
      - POSTGRES_PORT=${POSTGRES_PORT:-5432}
      - REDIS_HOST=${REDIS_HOST:-cache}
      - REDIS_PORT=${REDIS_PORT:-6379}
      - APP_PORT=${APP_PORT:-8000}
    depends_on:
      db:
        condition: service_healthy
    command:
      - "/bin/sh /docker-entrypoint.sh"
