# Generated by Django 3.2.13 on 2022-06-22 04:13

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0002_alter_uploadedimage_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="ImageUrl",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("expire", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "image",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="images.uploadedimage",
                    ),
                ),
                (
                    "preset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="images.imagepreset",
                    ),
                ),
            ],
            options={
                "unique_together": {("preset", "image")},
            },
        ),
    ]
