# Generated by Django 3.2.13 on 2022-06-26 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0003_imageurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageurl',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
