# Generated by Django 3.2.13 on 2022-06-27 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0004_imageurl_updated_at'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='imageurl',
            unique_together=set(),
        ),
    ]
